// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.1.0.0
//      SpecFlow Generator Version:3.1.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace GloboImprensa.Feature
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("Cadastrar no site Globo Imprensa", Description="Narrativa:\r\n\t\t\tEu como usuário \r\n\t\t\tQuero Cadastrar no site Globo Imprensa\r\n\t\t\tPa" +
        "ra acessar a home", SourceFile="Feature\\GloboImpressa01.feature", SourceLine=2)]
    public partial class CadastrarNoSiteGloboImprensaFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "GloboImpressa01.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Cadastrar no site Globo Imprensa", "Narrativa:\r\n\t\t\tEu como usuário \r\n\t\t\tQuero Cadastrar no site Globo Imprensa\r\n\t\t\tPa" +
                    "ra acessar a home", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void CadastrarNoGloboImprensaComSucesso(
                    string firstName, 
                    string lastName, 
                    string nickname, 
                    string sex, 
                    string email, 
                    string office, 
                    string publishingCompany, 
                    string carrier, 
                    string country, 
                    string state, 
                    string city, 
                    string dDDTelephone, 
                    string telephone, 
                    string dDDCellPhone, 
                    string cellPhone, 
                    string instagram, 
                    string twitter, 
                    string password, 
                    string repeatPassword, 
                    string message, 
                    string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cadastrar no Globo Imprensa com sucesso", null, exampleTags);
#line 10
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 12
  testRunner.Given("que eu navegue para tela de cadastro", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 13
  testRunner.When(string.Format("preencho  os campos de {0}, {1}, {2}, {3}, {4}, {5} ,{6}, {7}, {8}, {9}, {10}, {1" +
                            "1}, {12}, {13}, {14}, {15}, {16}, {17} e {18}", firstName, lastName, nickname, sex, email, office, publishingCompany, carrier, country, state, city, dDDTelephone, telephone, dDDCellPhone, cellPhone, instagram, twitter, password, repeatPassword), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 14
  testRunner.And("Clico em SOLICITAR CADASTRO", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 15
  testRunner.Then(string.Format("aguarda a {0} com sucesso", message), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Cadastrar no Globo Imprensa com sucesso, Thamires", SourceLine=20)]
        public virtual void CadastrarNoGloboImprensaComSucesso_Thamires()
        {
#line 10
this.CadastrarNoGloboImprensaComSucesso("Thamires", "Fernandes", "Mendes", "Feminino", "T87er7tyy38@gmail.com", "Editor", "Cultura / Entretenimento", "Teste", "Brasil", "RJ - Rio de Janeiro", "Tanguá", "21", "21897656", "21", "23467809", "thayn", "theuu", "Thatha9897@", "Thatha9897@", "Seu cadastro foi realizado. Aguarde a revisão e aprovação da sua conta.", ((string[])(null)));
#line hidden
        }
        
        public virtual void CadastrarNoGloboImprensaSemSucesso(
                    string firstName, 
                    string lastName, 
                    string nickname, 
                    string sex, 
                    string email, 
                    string office, 
                    string publishingCompany, 
                    string carrier, 
                    string country, 
                    string state, 
                    string city, 
                    string dDDTelephone, 
                    string telephone, 
                    string dDDCellPhone, 
                    string cellPhone, 
                    string instagram, 
                    string twitter, 
                    string password, 
                    string repeatPassword, 
                    string message, 
                    string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cadastrar no Globo Imprensa sem sucesso", null, exampleTags);
#line 24
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 26
  testRunner.Given("que eu navegue para tela de cadastro", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 27
  testRunner.When(string.Format("preencho  os campos de {0}, {1}, {2}, {3}, {4}, {5} ,{6}, {7}, {8}, {9}, {10}, {1" +
                            "1}, {12}, {13}, {14}, {15}, {16}, {17} e {18}", firstName, lastName, nickname, sex, email, office, publishingCompany, carrier, country, state, city, dDDTelephone, telephone, dDDCellPhone, cellPhone, instagram, twitter, password, repeatPassword), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 28
  testRunner.And("Clico em SOLICITAR CADASTRO", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 29
  testRunner.Then(string.Format("aguarda a {0} sem sucesso", message), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Cadastrar no Globo Imprensa sem sucesso, Variant 0", SourceLine=35)]
        public virtual void CadastrarNoGloboImprensaSemSucesso_Variant0()
        {
#line 24
this.CadastrarNoGloboImprensaSemSucesso("Thamires", "Fernandes", "Mendes", "Feminino", "T4tywe89338@gmail.com", "Editor", "Cultura / Entretenimento", "Teste", "Brasil", "RJ - Rio de Janeiro", "Tanguá", "21", "21897656", "21", "23467809", "thayn", "theuu", "Thatha9897@", "Thatha9897@", "Já existe um cadastro com este e-mail.", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Cadastrar no Globo Imprensa sem sucesso, Variant 1", SourceLine=35)]
        public virtual void CadastrarNoGloboImprensaSemSucesso_Variant1()
        {
#line 24
this.CadastrarNoGloboImprensaSemSucesso("", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "Solicitação de cadastro", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Cadastrar no Globo Imprensa sem sucesso, Variant 2", SourceLine=35)]
        public virtual void CadastrarNoGloboImprensaSemSucesso_Variant2()
        {
#line 24
this.CadastrarNoGloboImprensaSemSucesso("Carlar", "", "Caca", "Feminino", "T8ryy3w@gmail.com", "Editor", "Cultura / Entretenimento", "Teste", "21", "21897656", "21", "23467809", "21897656", "21", "23467809", "thayn", "theuu", "Thatha9897$", "Thatha9897$", "Solicitação de cadastro", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Cadastrar no Globo Imprensa sem sucesso, Variant 3", SourceLine=35)]
        public virtual void CadastrarNoGloboImprensaSemSucesso_Variant3()
        {
#line 24
this.CadastrarNoGloboImprensaSemSucesso("Carlar", "Costa", "Caca", "Feminino", "", "Editor", "Cultura / Entretenimento", "Teste", "21", "21897656", "21", "23467809", "21897656", "21", "23467809", "thayn", "theuu", "Thatha9897$", "Thatha9897$", "Solicitação de cadastro", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Cadastrar no Globo Imprensa sem sucesso, Variant 4", SourceLine=35)]
        public virtual void CadastrarNoGloboImprensaSemSucesso_Variant4()
        {
#line 24
this.CadastrarNoGloboImprensaSemSucesso("Carlar", "Costa", "Caca", "Feminino", "4576ut76@gmail.com", "Editor", "Cultura / Entretenimento", "Teste", "21", "21897656", "21", "23467809", "21897656", "21", "23467809", "thayn", "theuu", "Thatha9897$", "", "Solicitação de cadastro", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Cadastrar no Globo Imprensa sem sucesso, Variant 5", SourceLine=35)]
        public virtual void CadastrarNoGloboImprensaSemSucesso_Variant5()
        {
#line 24
this.CadastrarNoGloboImprensaSemSucesso("Carlar", "Costa", "Caca", "Feminino", "i87uiy5667@gmail.com", "Editor", "Cultura / Entretenimento", "Teste", "21", "21897656", "21", "23467809", "21897656", "21", "23467809", "thayn", "theuu", "", "Thatha9897$", "Solicitação de cadastro", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
